# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/krists/Documents/git/face-detector-loopback

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/krists/Documents/git/face-detector-loopback

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/krists/Documents/git/face-detector-loopback/CMakeFiles /home/krists/Documents/git/face-detector-loopback//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/krists/Documents/git/face-detector-loopback/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenCVTest

# Build rule for target.
OpenCVTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OpenCVTest
.PHONY : OpenCVTest

# fast build rule for target.
OpenCVTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCVTest.dir/build.make CMakeFiles/OpenCVTest.dir/build
.PHONY : OpenCVTest/fast

#=============================================================================
# Target rules for targets named FaceTest

# Build rule for target.
FaceTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FaceTest
.PHONY : FaceTest

# fast build rule for target.
FaceTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FaceTest.dir/build.make CMakeFiles/FaceTest.dir/build
.PHONY : FaceTest/fast

#=============================================================================
# Target rules for targets named LoopbackCameraTest

# Build rule for target.
LoopbackCameraTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LoopbackCameraTest
.PHONY : LoopbackCameraTest

# fast build rule for target.
LoopbackCameraTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LoopbackCameraTest.dir/build.make CMakeFiles/LoopbackCameraTest.dir/build
.PHONY : LoopbackCameraTest/fast

#=============================================================================
# Target rules for targets named FaceDetectorLoopback

# Build rule for target.
FaceDetectorLoopback: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FaceDetectorLoopback
.PHONY : FaceDetectorLoopback

# fast build rule for target.
FaceDetectorLoopback/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FaceDetectorLoopback.dir/build.make CMakeFiles/FaceDetectorLoopback.dir/build
.PHONY : FaceDetectorLoopback/fast

src/face-detector-loopback.o: src/face-detector-loopback.cpp.o
.PHONY : src/face-detector-loopback.o

# target to build an object file
src/face-detector-loopback.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FaceDetectorLoopback.dir/build.make CMakeFiles/FaceDetectorLoopback.dir/src/face-detector-loopback.cpp.o
.PHONY : src/face-detector-loopback.cpp.o

src/face-detector-loopback.i: src/face-detector-loopback.cpp.i
.PHONY : src/face-detector-loopback.i

# target to preprocess a source file
src/face-detector-loopback.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FaceDetectorLoopback.dir/build.make CMakeFiles/FaceDetectorLoopback.dir/src/face-detector-loopback.cpp.i
.PHONY : src/face-detector-loopback.cpp.i

src/face-detector-loopback.s: src/face-detector-loopback.cpp.s
.PHONY : src/face-detector-loopback.s

# target to generate assembly for a file
src/face-detector-loopback.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FaceDetectorLoopback.dir/build.make CMakeFiles/FaceDetectorLoopback.dir/src/face-detector-loopback.cpp.s
.PHONY : src/face-detector-loopback.cpp.s

src/face-detector-test.o: src/face-detector-test.cpp.o
.PHONY : src/face-detector-test.o

# target to build an object file
src/face-detector-test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FaceTest.dir/build.make CMakeFiles/FaceTest.dir/src/face-detector-test.cpp.o
.PHONY : src/face-detector-test.cpp.o

src/face-detector-test.i: src/face-detector-test.cpp.i
.PHONY : src/face-detector-test.i

# target to preprocess a source file
src/face-detector-test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FaceTest.dir/build.make CMakeFiles/FaceTest.dir/src/face-detector-test.cpp.i
.PHONY : src/face-detector-test.cpp.i

src/face-detector-test.s: src/face-detector-test.cpp.s
.PHONY : src/face-detector-test.s

# target to generate assembly for a file
src/face-detector-test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FaceTest.dir/build.make CMakeFiles/FaceTest.dir/src/face-detector-test.cpp.s
.PHONY : src/face-detector-test.cpp.s

src/loopback-camera-test.o: src/loopback-camera-test.cpp.o
.PHONY : src/loopback-camera-test.o

# target to build an object file
src/loopback-camera-test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LoopbackCameraTest.dir/build.make CMakeFiles/LoopbackCameraTest.dir/src/loopback-camera-test.cpp.o
.PHONY : src/loopback-camera-test.cpp.o

src/loopback-camera-test.i: src/loopback-camera-test.cpp.i
.PHONY : src/loopback-camera-test.i

# target to preprocess a source file
src/loopback-camera-test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LoopbackCameraTest.dir/build.make CMakeFiles/LoopbackCameraTest.dir/src/loopback-camera-test.cpp.i
.PHONY : src/loopback-camera-test.cpp.i

src/loopback-camera-test.s: src/loopback-camera-test.cpp.s
.PHONY : src/loopback-camera-test.s

# target to generate assembly for a file
src/loopback-camera-test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LoopbackCameraTest.dir/build.make CMakeFiles/LoopbackCameraTest.dir/src/loopback-camera-test.cpp.s
.PHONY : src/loopback-camera-test.cpp.s

src/opencv-test.o: src/opencv-test.cpp.o
.PHONY : src/opencv-test.o

# target to build an object file
src/opencv-test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCVTest.dir/build.make CMakeFiles/OpenCVTest.dir/src/opencv-test.cpp.o
.PHONY : src/opencv-test.cpp.o

src/opencv-test.i: src/opencv-test.cpp.i
.PHONY : src/opencv-test.i

# target to preprocess a source file
src/opencv-test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCVTest.dir/build.make CMakeFiles/OpenCVTest.dir/src/opencv-test.cpp.i
.PHONY : src/opencv-test.cpp.i

src/opencv-test.s: src/opencv-test.cpp.s
.PHONY : src/opencv-test.s

# target to generate assembly for a file
src/opencv-test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenCVTest.dir/build.make CMakeFiles/OpenCVTest.dir/src/opencv-test.cpp.s
.PHONY : src/opencv-test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FaceDetectorLoopback"
	@echo "... FaceTest"
	@echo "... LoopbackCameraTest"
	@echo "... OpenCVTest"
	@echo "... src/face-detector-loopback.o"
	@echo "... src/face-detector-loopback.i"
	@echo "... src/face-detector-loopback.s"
	@echo "... src/face-detector-test.o"
	@echo "... src/face-detector-test.i"
	@echo "... src/face-detector-test.s"
	@echo "... src/loopback-camera-test.o"
	@echo "... src/loopback-camera-test.i"
	@echo "... src/loopback-camera-test.s"
	@echo "... src/opencv-test.o"
	@echo "... src/opencv-test.i"
	@echo "... src/opencv-test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

